name: Default
on:
  pull_request:
  push:
    branches:
      - main
env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  DOTNET_CONSOLE_ANSI_COLOR: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://pub.ryon.ren/actions/checkout@v3
      - name: Setup Dotnet
        uses: https://pub.ryon.ren/actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: "**/packages.lock.json"
      - run: dotnet restore --locked-mode
      - run: dotnet build --configuration Release --no-restore
      - run: dotnet test --configuration Release --no-restore
