name: Default
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*"
env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  DOTNET_CONSOLE_ANSI_COLOR: true
  DOTNET_INSTALL_DIR: ${{ github.workspace }}/.dotnet

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://pub.ryon.ren/actions/checkout@v3
      - name: Cache Dotnet Install
        id: cache-dotnet-install
        uses: https://pub.ryon.ren/actions/cache@v3
        with:
          path: ${{ env.DOTNET_INSTALL_DIR }}
          key: dotnet-${{ runner.os }}-8.0.x
      - name: Cache Nuget Packages
        uses: https://pub.ryon.ren/actions/cache@v3
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.lock.json') }}
      - name: Setup Dotnet
        if: steps.cache-dotnet-install.outputs.cache-hit != 'true'
        uses: https://pub.ryon.ren/actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Set PATH
        run: |
          echo "::add-path::${{ env.DOTNET_INSTALL_DIR }}"
      - name: Restore
        if: steps.cache-nuget-packages.outputs.cache-hit != 'true'
        run: dotnet restore --locked-mode -s https://nuget.cdn.azure.cn/v3/index.json
      - run: dotnet build --configuration Release --no-restore
      - name: Collect Artifacts if failed
        if: failure() && github.ref == 'refs/heads/main'
        uses: https://pub.ryon.ren/actions/upload-artifact@v3
        with:
          path: |
            ${{ github.workspace }}
            !${{ github.workspace }}/.git
            !${{ github.workspace }}/.nuget
            !${{ github.workspace }}/.dotnet

      - run: dotnet test --configuration Release --no-restore
      - name: Push Nuget Packages
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          dotnet pack src/Furzn/Furzn.fsproj --configuration Release --no-restore
          dotnet nuget push bld/bin/Furzn/Release/*.nupkg --source https://ryon.ren/api/packages/${{ github.repository_owner }}/nuget/index.json --api-key ${{ github.token }}
